import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { fetchHeaderData } from "@/services/header.service";
import _get from "lodash/get";
import { fetchFooterData } from "@/services/footer.service";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const fetchedheaderData = await fetchHeaderData();
  const fetchedfooterData = await fetchFooterData();

  const headerData = _get(fetchedheaderData, "header", {});
  const footerData = _get(fetchedfooterData, "", fetchedfooterData);

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
      >
        <Header headerData={headerData}/>
        {children}
        <Footer footerData={footerData} />
      </body>
    </html>
  );
}
